name: flutter_fy
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  diacritic: ^0.1.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  lucide_icons_flutter: ^3.1.1
  mask_text_input_formatter: ^2.9.0
  meta: ^1.15.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  
